### PR TITLE
Update GitHub actions to use newly created installation routine (aka. new install script)

### PR DESCRIPTION
**Pull request by D3PSI**
Utilize the new installer in GitHub actions to get notifications if it is broken with Debian.

### CODE REVIEW

**Comment by Hopson97** [comment]
Trying locally, it seems the install script should be ran like

`sudo bash scripts/install.sh`

https://stackoverflow.com/questions/3401183/bash-syntax-error-not-found

**Comment by D3PSI** [comment]
I have already noticed that and added it into the PR. Thank you :)!

**Comment by D3PSI** [comment]
I have also already updated the README.md to avoid confusion.

**Comment by Hopson97** [comment]
Awesome, thanks for this!

**Pull request merged**
