### PR TITLE
Update to gcc-8 for <filesystem> and <optional>

### PR DESCRIPTION
**Pull request by D3PSI**
In response to #174.

### CODE REVIEW

**Comment by D3PSI** [comment]
Wait, somehow this does not work

**Comment by D3PSI** [comment]
The thing is, if you export the CC and CXX environment variables in the install script, the clang++ build will be built with g++...

**Comment by D3PSI** [comment]
This is exactly how I did it in my project, but it does not seem to work here. Does the `scripts/build.sh` somehow export to the environment variables C and CXX?

**Comment by Hopson97** [comment]
Shouldn't do as far as I know, it only runs cmake and then make

**Comment by D3PSI** [comment]
Alright, apparently that fixed it. The mistake was this: if I export to environment variables from the install script, these updated environment variables will obviously not be updated outside of the shell of the script. So the install scripts gets run once with the `--no-build` flag, does thus not run the `scripts/build.sh` script. It exits. A new shell gets spawned when `scripts/build.sh` is run. That shell will not overtake the updated values of the environment variables as these 'died' with the old shell. It's fixed now.

**Comment by D3PSI** [comment]
What you have to take into account though is that by exporting to the compiler environment variables you prohibit GitHub Actions from compiling with a different compiler aka Clang in this case. So, I went ahead and deleted the job for the Clang-compilation because it is rendered obsolete by this export to environment variables. It is an 'unpretty' fix, if you insisted on having a Clang-compilation (which I don't think is really necessary) we would have to come up with another solution.

**Comment by Hopson97** [comment]
Having just g++ is probably fine. 

Also, just want to say thanks so much for your contributions this project, your additions have been very useful :)

**Comment by D3PSI** [comment]
Anytime, it's a pleasure ;)

**Pull request merged**
