### PR TITLE
Changed default block textures to something pretty

### PR DESCRIPTION
**Pull request by rehwinkel**
I created a new (hopefully prettier) texture for all of the blocks.

### CODE REVIEW

**Comment by Hopson97** [comment]
Hi, thanks for this! 

However, Is it ok if this can instead be made as a separate texture pack? I added them into the game for this reason, so people would easily be able to switch them out rather than override the existing textures.

**Comment by Hopson97** [comment]
Hi, thanks for this! 

However, Is it ok if this can instead be made as a separate texture pack? I added them into the game for this reason, so people would easily be able to switch them out rather than override the existing textures.

**Comment by Hopson97** [comment]
This can be done by adding a new folder to the texture_packs folder, and putting your textures in there.

Then in `config.obd` you can change the `texture_pack` value to a different pack.

**Comment by Hopson97** [comment]
[default1.zip](https://github.com/Hopson97/open-builder/files/4083551/default1.zip)

In case access to old textures has been lost, you can download them here ^ To be put back into texture pack 1

**Comment by rehwinkel** [comment]
So I removed the last two commits from my branch and overwrote them with a commit where I add my textures as a separate texture pack. Probably not the best way, but shouldn't cause any issues when merging. And here's a screenshot too:
Screenshot

**Comment by Hopson97** [comment]
If it works, it works. They look really nice, thanks! Merging now.

**Pull request merged**
