### PR TITLE
Fix variable name

### PR DESCRIPTION
**Pull request by hebriel**
I really want to contribute in other ways, I swear! :)

### CODE REVIEW

**Comment by Hopson97** [comment]
Right :P I'll try to come up with something. For the next week or so, I am not really adding any features, however I am doing some code refactoring and that.

I guess if you see something in the code that you think could be better, then let me know and you can help out :)

One thing in the code I am trying to work out is this struct here:

https://github.com/Hopson97/open-builder/blob/master/src/client/client_state.h

The Client and Gameplay classes used to be combined, but I split them out to separate the network code from the game-play code, but then I had the issue that the network code needed to interact with some data used by the game play, so I made the ClientState struct. However, I feel there's definitely a better way, but I am unsure.

(Trying to work out a decent way to seperate out the network from the gameplay, one simple way is I could re-combine them, and just move network code to a seperate .cpp file, but that feels pretty bad lol so idk)



(Not adding features as I don't have access to my usual set up so I won't be able to make videos until then anyway :P)

**Comment by Hopson97** [comment]
The issue is having this shared struct makes it a lot harder to make the code concurrent. 

Ideally, the construction of the chunk meshes should done by worker threads. I know this from experience creating voxel games in the past, creating them in the main thread can really harm the FPS.

But now I am making a voxel game ft networking, so things are a bit more complicated :p

**Comment by Hopson97** [comment]
I mean that's what I am working on for now, you can see my progress in the branch `concurrent-client`

https://github.com/Hopson97/open-builder/tree/refactor/concurrent-client

So yeahh anyways, feel free to help out wherever you want for now in terms of improving the code :P

**Comment by hebriel** [comment]
For now I started working on adding Gamepad support :)
I'll check that file, but I have 0 background in Network programming and Concurrent programming, so I don't know if I'll be super useful on that one

**Comment by Hopson97** [comment]
Ahh that is something I actually don't have planned, plus that would be very good for the game :) 

And that is ok, thanks for the help!

**Pull request merged**
